### Buscar todos los productos

GET http://localhost:4010/products/



### Buscar un productos por su Id
GET http://localhost:4010/products/65635157b606a43274843682



### Crear un producto
POST http://localhost:4010/products/
Content-Type: application/json

{
  "name": "Lima limon",
  "category": "Bebida",
  "price": 1200

}

### Actualizar el Producto
PUT http://localhost:4010/products/65635157b606a43274843682
Content-Type: application/json

{
  "name": "Hola que tal",
  "price": 3111100

}

### Eliminar el producto
DELETE  http://localhost:4010/products/65635136489e208742f6a4ab
